import assert from 'node:assert/strict';
import test from 'node:test';

const base=process.env.TEST_API_URL||'http://127.0.0.1:4000/api';
const password=process.env.TEST_PASSWORD||'Demo@2026!';
const roles=['citizen','staff','supervisor','admin'] as const;
async function login(role:typeof roles[number]){const response=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:`${role}@ecoclean.sl`,password})});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie');assert.ok(cookie?.includes('HttpOnly'));return cookie!.split(';')[0];}
const get=(path:string,cookie:string)=>fetch(`${base}${path}`,{headers:{cookie}});

test('health confirms database connectivity',async()=>{const response=await fetch(`${base}/health`);assert.equal(response.status,200);assert.equal((await response.json() as any).database,'connected');});
test('all four roles authenticate and restore sessions',async()=>{for(const role of roles){const cookie=await login(role);const response=await get('/auth/me',cookie);assert.equal(response.status,200);assert.ok((await response.json() as any).user.role);}});
test('authenticated profile includes database identity and phone login works',async()=>{const phoneResponse=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier:'+23276000001',password})});assert.equal(phoneResponse.status,200);const cookie=phoneResponse.headers.get('set-cookie')!.split(';')[0];const me=await get('/auth/me',cookie);assert.equal(me.status,200);const user=(await me.json() as any).user;assert.ok(user.fullName);assert.equal(user.phone,'+23276000001');assert.equal(user.role,'citizen');assert.ok('profileImageUrl' in user);assert.ok('municipality' in user);assert.ok(user.roleLabel);});
test('citizen is denied administrator monitoring',async()=>{const response=await get('/operations/health',await login('citizen'));assert.equal(response.status,403);});
test('administrator reaches normalized Phase 4 services',async()=>{const cookie=await login('admin');for(const endpoint of ['/operations/health','/support/metrics','/rewards','/campaigns','/community/posts','/fleet/vehicles','/assets','/contractors','/documents','/notifications/providers','/backups','/gis/layers','/gis/markers','/gis/boundaries','/gis/communities','/security/events','/uploads/scans','/auth/sessions'])assert.equal((await get(endpoint,cookie)).status,200,endpoint);});
test('upload rejects requests without valid files',async()=>{const response=await fetch(`${base}/uploads`,{method:'POST',headers:{cookie:await login('citizen')}});assert.equal(response.status,422);});
test('citizen report submit accepts every valid district UI municipality label',async()=>{const cookie=await login('citizen');const response=await fetch(`${base}/reports-operational`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({title:'Submit workflow validation',description:'Confirms that the report submit action persists the selected Sierra Leone district.',category:'Illegal Dumping',latitude:7.9628,longitude:-11.7401,address:'Bo City validation point',districtName:'Bo District',municipalityName:'Bo City Council (BCC)',wardName:'Ward 301',zoneName:'Zone 1'})});assert.equal(response.status,201);const created=(await response.json() as any).data;assert.ok(created.id);assert.match(created.reference,/^ECO-\d{4}-\d{6}$/);assert.equal(created.municipalityName,'Bo District Council');const reports=await get('/reports-scoped',cookie);assert.equal(reports.status,200);assert.ok((await reports.json() as any).data.some((row:any)=>row.id===created.id));});
test('supervisor/admin submit actions persist messages, broadcasts, and settings',async()=>{const supervisor=await login('supervisor');const staffDirectory=await get('/staff-directory',supervisor);assert.equal(staffDirectory.status,200);const staff=(await staffDirectory.json() as any).data[0];assert.ok(staff?.id);const direct=await fetch(`${base}/notifications/direct`,{method:'POST',headers:{cookie:supervisor,'content-type':'application/json'},body:JSON.stringify({userId:staff.id,title:'Button audit instruction',body:'Confirmed persistent supervisor-to-staff message.'})});assert.equal(direct.status,201);const broadcast=await fetch(`${base}/announcements`,{method:'POST',headers:{cookie:supervisor,'content-type':'application/json'},body:JSON.stringify({title:'Button audit broadcast',body:'Confirmed persistent municipal broadcast.'})});assert.equal(broadcast.status,201);const admin=await login('admin');const settings=await fetch(`${base}/system/settings/button_audit`,{method:'PUT',headers:{cookie:admin,'content-type':'application/json'},body:JSON.stringify({value:{verified:true}})});assert.equal(settings.status,204);const loaded=await get('/system/settings',admin);assert.equal((await loaded.json() as any).data.button_audit.verified,true);});
test('professional report exports enforce roles, scope, and formats',async()=>{const admin=await login('admin');const csv=await get('/reports/export-professional?format=csv',admin);assert.equal(csv.status,200);assert.match(csv.headers.get('content-type')||'',/text\/csv/);assert.match(await csv.text(),/Reference/);const pdf=await get('/reports/export-professional?format=pdf',admin);assert.equal(pdf.status,200);assert.match(pdf.headers.get('content-type')||'',/application\/pdf/);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');for(const format of ['xlsx','docx','json','geojson'])assert.equal((await get(`/reports/export-professional?format=${format}`,admin)).status,200,format);assert.equal((await get('/reports/export-professional?format=csv',await login('supervisor'))).status,200);assert.equal((await get('/reports/export-professional?format=csv',await login('citizen'))).status,403);});
