import assert from 'node:assert/strict';
import test from 'node:test';

const base=process.env.TEST_API_URL||'http://127.0.0.1:4000/api';
const password=process.env.TEST_PASSWORD||'Demo@2026!';
const roles=['citizen','staff','supervisor','admin'] as const;
async function login(role:typeof roles[number]){const response=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:`${role}@ecoclean.sl`,password})});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie');assert.ok(cookie?.includes('HttpOnly'));return cookie!.split(';')[0];}
const get=(path:string,cookie:string)=>fetch(`${base}${path}`,{headers:{cookie}});

test('health confirms database connectivity',async()=>{const response=await fetch(`${base}/health`);assert.equal(response.status,200);assert.equal((await response.json() as any).database,'connected');});
test('all four roles authenticate and restore sessions',async()=>{for(const role of roles){const cookie=await login(role);const response=await get('/auth/me',cookie);assert.equal(response.status,200);assert.ok((await response.json() as any).user.role);}});
test('authenticated profile includes database identity and phone login works',async()=>{const phoneResponse=await fetch(`${base}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier:'+23276000001',password})});assert.equal(phoneResponse.status,200);const cookie=phoneResponse.headers.get('set-cookie')!.split(';')[0];const me=await get('/auth/me',cookie);assert.equal(me.status,200);const user=(await me.json() as any).user;assert.ok(user.fullName);assert.equal(user.phone,'+23276000001');assert.equal(user.role,'citizen');assert.ok('profileImageUrl' in user);assert.ok('municipality' in user);assert.ok(user.roleLabel);});
test('citizen is denied administrator monitoring',async()=>{const response=await get('/operations/health',await login('citizen'));assert.equal(response.status,403);});
test('administrator reaches normalized Phase 4 services',async()=>{const cookie=await login('admin');for(const endpoint of ['/operations/health','/support/metrics','/rewards','/campaigns','/community/posts','/fleet/vehicles','/assets','/contractors','/documents','/notifications/providers','/backups','/gis/layers','/gis/markers','/gis/boundaries','/gis/communities','/security/events','/uploads/scans','/auth/sessions'])assert.equal((await get(endpoint,cookie)).status,200,endpoint);});
test('upload rejects requests without valid files',async()=>{const response=await fetch(`${base}/uploads`,{method:'POST',headers:{cookie:await login('citizen')}});assert.equal(response.status,422);});
test('professional report exports enforce roles, scope, and formats',async()=>{const admin=await login('admin');const csv=await get('/reports/export-professional?format=csv',admin);assert.equal(csv.status,200);assert.match(csv.headers.get('content-type')||'',/text\/csv/);assert.match(await csv.text(),/Reference/);const pdf=await get('/reports/export-professional?format=pdf',admin);assert.equal(pdf.status,200);assert.match(pdf.headers.get('content-type')||'',/application\/pdf/);assert.equal(Buffer.from(await pdf.arrayBuffer()).subarray(0,4).toString(),'%PDF');for(const format of ['xlsx','docx','json','geojson'])assert.equal((await get(`/reports/export-professional?format=${format}`,admin)).status,200,format);assert.equal((await get('/reports/export-professional?format=csv',await login('supervisor'))).status,200);assert.equal((await get('/reports/export-professional?format=csv',await login('citizen'))).status,403);});
