import assert from 'node:assert/strict';
import bcrypt from 'bcryptjs';
import {pool} from '../server/db.js';

const base=process.env.TEST_API_URL||'http://127.0.0.1:4000/api';const seedPassword=process.env.TEST_PASSWORD||'Demo@2026!';const password='Phase45@2026!';const stamp=String(Date.now()).slice(-8);const evidence:any[]=[];
const request=(path:string,options:RequestInit={},cookie?:string)=>fetch(`${base}${path}`,{...options,headers:{...(options.body instanceof FormData?{}:{'content-type':'application/json'}),...(cookie?{cookie}:{}),...options.headers}});
async function login(email:string,pass=password){const response=await request('/auth/login',{method:'POST',body:JSON.stringify({email,password:pass})});return{response,cookie:response.headers.get('set-cookie')?.split(';')[0]||''};}
const national=await login('nationaladmin@ecoclean.sl',seedPassword);assert.equal(national.response.status,200);
const roles=['CITIZEN','STAFF','SUPERVISOR','ADMINISTRATOR','NATIONAL_ADMIN'] as const;const accounts:any={};
for(let index=0;index<roles.length;index++){const role=roles[index],email=`phase45.${role.toLowerCase()}.${stamp}@ecoclean.sl`,phone=`+23288${stamp.slice(0,6)}${index}`;const response=await request('/admin/users',{method:'POST',body:JSON.stringify({fullName:`Phase 45 ${role}`,email,phone,password,role,municipalityId:1,districtId:1})},national.cookie);assert.equal(response.status,201,`${role} creation`);const data=(await response.json() as any).data;accounts[role]={...data,email,phone};const session=await login(email);assert.equal(session.response.status,200,`${role} login`);accounts[role].cookie=session.cookie;}
const [created]=await pool.query<any[]>('SELECT u.id,u.email,u.phone,u.password_hash,r.code role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email LIKE ?',[`phase45.%${stamp}@ecoclean.sl`]);assert.equal(created.length,5);for(const row of created){assert.equal(await bcrypt.compare(password,row.password_hash),true);accounts[row.role].id=row.id;}
const duplicate=await request('/admin/users',{method:'POST',body:JSON.stringify({fullName:'Duplicate Account',email:accounts.CITIZEN.email,phone:'+232880000099',password,role:'CITIZEN'})},national.cookie);assert.equal(duplicate.status,409);evidence.push({module:'registration',roles:created.map(row=>row.role),bcryptVerified:5,duplicateStatus:duplicate.status});

for(const role of roles){const account=accounts[role];const profileResponse=await request('/profile',{},account.cookie);assert.equal(profileResponse.status,200);const update=await request('/profile',{method:'PATCH',body:JSON.stringify({fullName:`Validated ${role}`,email:account.email,phone:account.phone,address:'45 Validation Road',municipalityId:1,districtId:1,emergencyContactName:'Emergency Contact',emergencyContactPhone:'+23277000000',biography:`Validated ${role} biography`})},account.cookie);assert.equal(update.status,200);const preferences=await request('/profile/preferences',{method:'PUT',body:JSON.stringify({theme:'dark',language:'en',notificationPreferences:{email:true,sms:false},gisPreferences:{zoom:12,shareLocation:true},dashboardPreferences:{compact:false}})},account.cookie);assert.equal(preferences.status,204);}
const [profileRows]=await pool.query<any[]>("SELECT COUNT(*) total,SUM(p.address='45 Validation Road') addresses,SUM(pref.theme='dark') themes FROM users u JOIN user_profiles p ON p.user_id=u.id JOIN user_preferences pref ON pref.user_id=u.id WHERE u.email LIKE ?",[`phase45.%${stamp}@ecoclean.sl`]);assert.equal(Number(profileRows[0].addresses),5);assert.equal(Number(profileRows[0].themes),5);evidence.push({module:'profiles',...profileRows[0]});

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
async function upload(cookie:string,purpose:string,relations:Record<string,string|number>={}){const form=new FormData();form.append('purpose',purpose);form.append('files',new Blob([png],{type:'image/png'}),`${purpose}.png`);for(const [key,value] of Object.entries(relations))form.append(key,String(value));return request('/uploads',{method:'POST',body:form},cookie);}
for(const role of roles){const uploaded=await upload(accounts[role].cookie,'profile_image');assert.equal(uploaded.status,201,`${role} photo`);accounts[role].photo=(await uploaded.json() as any).data[0];const retrieved=await request(`/uploads/${accounts[role].photo.id}`,{},accounts[role].cookie);assert.equal(retrieved.status,200);assert.equal(Buffer.from(await retrieved.arrayBuffer()).subarray(0,8).toString('hex'),'89504e470d0a1a0a');}
const firstCitizenPhoto=accounts.CITIZEN.photo.id;const replacement=await upload(accounts.CITIZEN.cookie,'profile_image');assert.equal(replacement.status,201);accounts.CITIZEN.photo=(await replacement.json() as any).data[0];assert.equal((await request(`/uploads/${firstCitizenPhoto}`,{},accounts.CITIZEN.cookie)).status,404);assert.equal((await request(`/uploads/${accounts.CITIZEN.photo.id}`,{},accounts.STAFF.cookie)).status,404);assert.equal((await request('/profile/photo',{method:'DELETE'},accounts.CITIZEN.cookie)).status,204);assert.equal((await request(`/uploads/${accounts.CITIZEN.photo.id}`,{},accounts.CITIZEN.cookie)).status,404);evidence.push({module:'profile_media',roleUploads:5,replacementProtected:true,crossUserDenied:true,deletionPersisted:true});

const reportResponse=await request('/reports',{method:'POST',body:JSON.stringify({title:'Phase 45 persistent evidence',description:'Permanent centrally stored validation report evidence.',category:'Illegal dumping',latitude:8.4844,longitude:-13.2344,address:'Validation Road'})},accounts.CITIZEN.cookie);assert.equal(reportResponse.status,201);const report=(await reportResponse.json() as any).data;const reportUpload=await upload(accounts.CITIZEN.cookie,'report_evidence',{reportId:report.id});assert.equal(reportUpload.status,201);const reportFile=(await reportUpload.json() as any).data[0];const detail=await request(`/reports/${report.id}`,{},accounts.CITIZEN.cookie);assert.equal(detail.status,200);assert.equal((await detail.json() as any).data.attachments.length,1);const download=await request(`/uploads/${reportFile.id}?download=1`,{},accounts.CITIZEN.cookie);assert.equal(download.status,200);assert.match(download.headers.get('content-disposition')||'',/attachment/);assert.equal((await request(`/uploads/${reportFile.id}`,{},accounts.STAFF.cookie)).status,404);
const corrupt=new FormData();corrupt.append('purpose','report_evidence');corrupt.append('reportId',String(report.id));corrupt.append('files',new Blob(['not-a-png'],{type:'image/png'}),'corrupt.png');assert.equal((await request('/uploads',{method:'POST',body:corrupt},accounts.CITIZEN.cookie)).status,422);const executable=new FormData();executable.append('purpose','report_evidence');executable.append('reportId',String(report.id));executable.append('files',new Blob(['MZ'],{type:'application/x-msdownload'}),'blocked.exe');assert.equal((await request('/uploads',{method:'POST',body:executable},accounts.CITIZEN.cookie)).status,422);

const taskResponse=await request('/tasks',{method:'POST',body:JSON.stringify({reportId:report.id,assignedTo:accounts.STAFF.id,title:'Phase 45 assigned cleanup',description:'Evidence workflow validation',priority:'high'})},accounts.SUPERVISOR.cookie);assert.equal(taskResponse.status,201);const task=(await taskResponse.json() as any).data;assert.equal((await request(`/uploads/${reportFile.id}`,{},accounts.STAFF.cookie)).status,200);assert.equal((await request(`/reports/${report.id}`,{},accounts.STAFF.cookie)).status,200);assert.equal((await request(`/reports/${report.id}`,{},accounts.SUPERVISOR.cookie)).status,200);assert.equal((await request(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:'accepted',note:'Accepted in validation'})},accounts.STAFF.cookie)).status,200);const taskUpload=await upload(accounts.STAFF.cookie,'task_evidence',{taskId:task.id});assert.equal(taskUpload.status,201);assert.equal((await request(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:'completed',note:'Completion evidence attached'})},accounts.STAFF.cookie)).status,200);assert.equal((await request(`/tasks/${task.id}`,{method:'PATCH',body:JSON.stringify({status:'verified',note:'Supervisor verified evidence'})},accounts.SUPERVISOR.cookie)).status,200);assert.equal((await request(`/reports/${report.id}`,{method:'DELETE'},accounts.CITIZEN.cookie)).status,409);evidence.push({module:'report_task_media',reportId:report.id,reportUploadId:reportFile.id,taskId:task.id,ownerRetrieval:true,staffAssignmentAccess:true,supervisorJurisdictionAccess:true,corruptRejected:true,executableRejected:true});

const notifications=await request('/notifications',{},accounts.CITIZEN.cookie);const notificationRows=(await notifications.json() as any).data;assert.ok(notificationRows.length>0);assert.equal((await request(`/notifications/${notificationRows[0].id}/read`,{method:'PATCH'},accounts.CITIZEN.cookie)).status,204);assert.equal((await request('/notifications/mark-all-read',{method:'POST'},accounts.CITIZEN.cookie)).status,204);assert.equal((await request(`/notifications/${notificationRows[0].id}`,{method:'DELETE'},accounts.CITIZEN.cookie)).status,204);
const ticketResponse=await request('/support/tickets',{method:'POST',body:JSON.stringify({subject:'Phase 45 support request',category:'validation',priority:'medium',message:'Please validate the persistent conversation.'})},accounts.CITIZEN.cookie);assert.equal(ticketResponse.status,201);const ticket=(await ticketResponse.json() as any).data;assert.equal((await request(`/support/conversations/${ticket.conversationId}/messages`,{method:'POST',body:JSON.stringify({body:'Persistent citizen reply'})},accounts.CITIZEN.cookie)).status,201);assert.equal((await request(`/support/tickets/${ticket.id}/close`,{method:'POST'},accounts.CITIZEN.cookie)).status,204);evidence.push({module:'notifications_support',read:true,markAll:true,delete:true,ticketClosed:true,conversationPersisted:true});

const resetRequest=await request('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:accounts.CITIZEN.email})});assert.equal(resetRequest.status,200);const token=(await resetRequest.json() as any).developmentToken;assert.ok(token);const resetPassword='ResetPhase45@2026!';assert.equal((await request('/auth/reset-password',{method:'POST',body:JSON.stringify({token,password:resetPassword})})).status,200);assert.equal((await login(accounts.CITIZEN.email,password)).response.status,401);const resetLogin=await login(accounts.CITIZEN.email,resetPassword);assert.equal(resetLogin.response.status,200);assert.equal((await request('/auth/reset-password',{method:'POST',body:JSON.stringify({token,password:'AnotherPhase45@2026!'})})).status,422);
const staffChange=await request('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:password,newPassword:'ChangedPhase45@2026!'})},accounts.STAFF.cookie);assert.equal(staffChange.status,200);assert.equal((await login(accounts.STAFF.email,password)).response.status,401);assert.equal((await login(accounts.STAFF.email,'ChangedPhase45@2026!')).response.status,200);
const expired=await login(accounts.SUPERVISOR.email);assert.equal(expired.response.status,200);await pool.query('UPDATE user_sessions SET expires_at=DATE_SUB(NOW(),INTERVAL 1 SECOND) WHERE user_id=? AND revoked_at IS NULL',[accounts.SUPERVISOR.id]);assert.equal((await request('/auth/me',{},expired.cookie)).status,401);
const forced=await login(accounts.ADMINISTRATOR.email);assert.equal(forced.response.status,200);assert.equal((await request(`/auth/users/${accounts.ADMINISTRATOR.id}/revoke-sessions`,{method:'POST'},national.cookie)).status,204);assert.equal((await request('/auth/me',{},forced.cookie)).status,401);evidence.push({module:'authentication',resetTokenInvalidated:true,oldPasswordRejected:true,newPasswordAccepted:true,expiredSessionRejected:true,forcedLogout:true});

for(const role of roles){await request(`/admin/users/${accounts[role].id}`,{method:'PATCH',body:JSON.stringify({status:'disabled'})},national.cookie);}assert.equal((await login(accounts.CITIZEN.email,resetPassword)).response.status,401);
const [dbEvidence]=await pool.query<any[]>(`SELECT
 (SELECT COUNT(*) FROM audit_logs WHERE user_id IN (?)) audits,
 (SELECT COUNT(*) FROM uploads WHERE owner_user_id IN (?)) uploads,
 (SELECT COUNT(*) FROM report_history WHERE report_id=?) report_history,
 (SELECT COUNT(*) FROM task_history WHERE task_id=?) task_history,
 (SELECT COUNT(*) FROM messages WHERE conversation_id=?) messages`,[Object.values(accounts).map((account:any)=>account.id),Object.values(accounts).map((account:any)=>account.id),report.id,task.id,ticket.conversationId]);evidence.push({module:'database',...dbEvidence[0]});
console.log(JSON.stringify({testedAt:new Date().toISOString(),stamp,evidence},null,2));await pool.end();
