import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock, MessageSquare, Plus, Send, ShieldCheck, UserCheck } from 'lucide-react';
import { supportService } from '../../lib/services';
import type { User } from '../../types';

type Ticket={id:number;reference:string;subject:string;category:string;priority:string;status:string;conversation_id:number;opened_by_name:string;assigned_to_name?:string;created_at:string;updated_at:string};
type Message={id:number;body:string;sender_name:string;sender_role:string;created_at:string};

export default function ServiceCenter({user}:{user:User|null}){
  const [tickets,setTickets]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [messages,setMessages]=useState<Message[]>([]);
  const [subject,setSubject]=useState('');const [openingMessage,setOpeningMessage]=useState('');const [reply,setReply]=useState('');const [metrics,setMetrics]=useState<any>(null);const [error,setError]=useState('');
  const isCitizen=user?.role==='citizen';
  const load=async()=>{try{const {data}=await supportService.listTickets();setTickets(data);if(!isCitizen){const result=await supportService.metrics();setMetrics(result.data);}}catch{setError('Service Center data could not be loaded.');}};
  useEffect(()=>{void load();},[]);
  const openTicket=async()=>{if(subject.trim().length<3||openingMessage.trim().length<2)return;await supportService.createTicket({subject,category:'general',priority:'medium',message:openingMessage});setSubject('');setOpeningMessage('');await load();};
  const choose=async(ticket:Ticket)=>{setSelected(ticket);const {data}=await supportService.messages(ticket.conversation_id);setMessages(data);};
  const send=async()=>{if(!selected||!reply.trim())return;await supportService.sendMessage(selected.conversation_id,reply);setReply('');await choose(selected);};
  const update=async(payload:unknown)=>{if(!selected)return;await supportService.updateTicket(selected.id,payload);await load();setSelected(null);setMessages([]);};
  return <div className="space-y-6 font-sans">
    <div><span className="text-[10px] font-mono font-bold uppercase tracking-widest text-brand-primary">Official ECOCLEAN Service Center</span><h2 className="text-xl md:text-2xl font-extrabold text-gray-900 mt-1">Support & Communication</h2><p className="text-xs text-gray-500 mt-1">Secure, audited communication between citizens and ECOCLEAN operations teams.</p></div>
    {error&&<div className="p-3 rounded-xl bg-red-50 text-red-700 text-xs border border-red-100">{error}</div>}
    {!isCitizen&&metrics&&<div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['Total',metrics.summary.total],['Open',metrics.summary.open],['Assigned',metrics.summary.assigned],['Escalated',metrics.summary.escalated],['Resolved',metrics.summary.resolved]].map(([label,value])=><div key={String(label)} className="bg-white rounded-2xl border border-gray-100 p-4 shadow-sm"><span className="text-[10px] uppercase font-bold text-gray-400">{label}</span><div className="text-2xl font-black text-brand-primary mt-1">{Number(value||0)}</div></div>)}</div>}
    {isCitizen&&selected&&['open','resolved'].includes(selected.status)&&<div className="flex justify-end"><button onClick={()=>void supportService.closeTicket(selected.id).then(()=>{setSelected(null);return load();})} className="px-3 py-2 rounded-xl bg-gray-100 text-gray-700 text-xs font-bold">Close Selected Ticket</button></div>}
    {isCitizen&&<div className="bg-white rounded-2xl border border-gray-100 p-5 shadow-sm space-y-4"><h3 className="text-sm font-bold text-gray-900 flex items-center gap-2"><Plus className="w-4 h-4 text-brand-primary"/>Create Support Ticket</h3><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What do you need help with?" className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-brand-primary"/><textarea value={openingMessage} onChange={e=>setOpeningMessage(e.target.value)} placeholder="Describe your request" rows={3} className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-brand-primary"/><button onClick={()=>void openTicket()} className="bg-brand-primary text-white text-xs font-bold px-5 py-3 rounded-xl flex items-center gap-2"><Send className="w-4 h-4"/>Submit Request</button></div>}
    <div className="grid grid-cols-1 lg:grid-cols-5 gap-5"><div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-4 border-b border-gray-100"><h3 className="text-sm font-bold text-gray-900">{isCitizen?'My Tickets':'Ticket Queue'}</h3></div><div className="divide-y divide-gray-50 max-h-[520px] overflow-y-auto">{tickets.length===0?<p className="p-6 text-xs text-gray-400">No tickets available.</p>:tickets.map(ticket=><button key={ticket.id} onClick={()=>void choose(ticket)} className={`w-full text-left p-4 hover:bg-emerald-50/30 ${selected?.id===ticket.id?'bg-emerald-50/50':''}`}><div className="flex justify-between gap-2"><span className="text-xs font-mono font-bold text-brand-primary">{ticket.reference}</span><span className="text-[9px] font-bold uppercase px-2 py-1 rounded-full bg-gray-100 text-gray-600">{ticket.status}</span></div><h4 className="text-sm font-bold text-gray-900 mt-2">{ticket.subject}</h4><p className="text-[10px] text-gray-400 mt-1">{ticket.opened_by_name} • {ticket.priority} priority</p></button>)}</div></div>
    <div className="lg:col-span-3 bg-white rounded-2xl border border-gray-100 shadow-sm min-h-[430px]">{!selected?<div className="h-full min-h-[430px] flex flex-col items-center justify-center text-center p-8"><MessageSquare className="w-10 h-10 text-gray-200"/><p className="text-sm font-bold text-gray-500 mt-3">Select a ticket to open its conversation</p></div>:<div className="flex flex-col min-h-[520px]"><div className="p-4 border-b border-gray-100"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-bold text-gray-900">{selected.subject}</h3><p className="text-[10px] text-gray-400 mt-1">{selected.reference} • Assigned: {selected.assigned_to_name||'Unassigned'}</p></div><span className="text-[10px] font-bold uppercase text-brand-primary">{selected.status}</span></div>{!isCitizen&&<div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>void update({assignedTo:user?.id,status:'assigned'})} className="px-3 py-1.5 rounded-lg bg-emerald-50 text-brand-primary text-[10px] font-bold flex items-center gap-1"><UserCheck className="w-3 h-3"/>Assign to Me</button><button onClick={()=>void update({status:'escalated',priority:'high'})} className="px-3 py-1.5 rounded-lg bg-amber-50 text-amber-700 text-[10px] font-bold flex items-center gap-1"><AlertTriangle className="w-3 h-3"/>Escalate</button><button onClick={()=>void update({status:'resolved',resolution:'Resolved through the ECOCLEAN Service Center.'})} className="px-3 py-1.5 rounded-lg bg-blue-50 text-blue-700 text-[10px] font-bold flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/>Resolve</button></div>}</div><div className="flex-1 p-4 space-y-3 overflow-y-auto max-h-[340px]">{messages.map(message=><div key={message.id} className={`max-w-[85%] rounded-2xl p-3 ${message.sender_name===user?.fullName?'ml-auto bg-brand-primary text-white':'bg-gray-50 text-gray-700'}`}><p className="text-[10px] font-bold opacity-70">{message.sender_name} • {message.sender_role}</p><p className="text-xs mt-1 leading-relaxed">{message.body}</p><p className="text-[9px] opacity-50 mt-2 flex items-center gap-1"><Clock className="w-2.5 h-2.5"/>{String(message.created_at).slice(0,16)}</p></div>)}</div><div className="p-4 border-t border-gray-100 flex gap-2"><input value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send();}} placeholder="Write an audited reply…" className="flex-1 bg-gray-50 border border-gray-200 rounded-xl px-4 py-2.5 text-xs outline-none focus:border-brand-primary"/><button onClick={()=>void send()} className="bg-brand-primary text-white p-3 rounded-xl"><Send className="w-4 h-4"/></button></div></div>}</div></div>
    {!isCitizen&&metrics?.staff?.length>0&&<div className="bg-white rounded-2xl border border-gray-100 p-5 shadow-sm"><h3 className="text-sm font-bold text-gray-900 flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-brand-primary"/>Service Performance</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4">{metrics.staff.map((member:any)=><div key={member.id} className="p-3 bg-gray-50 rounded-xl"><span className="text-xs font-bold text-gray-800">{member.full_name}</span><p className="text-[10px] text-gray-400 mt-1">{Number(member.resolved||0)} resolved / {Number(member.assigned||0)} assigned</p></div>)}</div></div>}
  </div>;
}
