import { Router } from 'express';
import { z } from 'zod';
import { authenticate, authorize } from './auth.js';
import { createBackup, enforceRetention } from './backup.js';
import { pool } from './db.js';
import { processNotificationQueue } from './notificationProviders.js';
import { processUploadScans } from './uploadScanner.js';
import { runMaintenanceCycle } from './workers.js';

export const enterpriseRoutes = Router();
enterpriseRoutes.use(authenticate);
const managers=authorize('SUPERVISOR','ADMINISTRATOR','NATIONAL_ADMIN');
const admins=authorize('ADMINISTRATOR','NATIONAL_ADMIN');

enterpriseRoutes.get('/auth/sessions',async(req,res)=>{const [rows]=await pool.query('SELECT id,device_hash,ip_address,user_agent,last_seen_at,expires_at,created_at FROM user_sessions WHERE user_id=? AND revoked_at IS NULL AND expires_at>NOW() ORDER BY last_seen_at DESC',[req.authUser!.id]);res.json({data:rows});});
enterpriseRoutes.delete('/auth/sessions/:id',async(req,res)=>{await pool.query('UPDATE user_sessions SET revoked_at=NOW(),revoked_by=? WHERE id=? AND user_id=?',[req.authUser!.id,req.params.id,req.authUser!.id]);res.status(204).end();});
enterpriseRoutes.post('/auth/users/:id/revoke-sessions',admins,async(req,res)=>{await pool.query('UPDATE user_sessions SET revoked_at=NOW(),revoked_by=? WHERE user_id=? AND revoked_at IS NULL',[req.authUser!.id,req.params.id]);res.status(204).end();});

enterpriseRoutes.get('/rewards',async(req,res)=>{const [[points],[rewards],[transactions],[rankings]]=await Promise.all([pool.query('SELECT * FROM reward_points WHERE user_id=?',[req.authUser!.id]),pool.query('SELECT * FROM rewards WHERE active=TRUE ORDER BY points_cost'),pool.query('SELECT * FROM reward_transactions WHERE user_id=? ORDER BY created_at DESC LIMIT 100',[req.authUser!.id]),pool.query('SELECT rr.*,u.full_name FROM reward_rankings rr JOIN users u ON u.id=rr.user_id ORDER BY period_key DESC,rank_position LIMIT 100')]);res.json({data:{points:(points as any[])[0]||{balance:0,lifetime_earned:0},rewards,transactions,rankings}});});
enterpriseRoutes.post('/rewards/:id/redeem',async(req,res)=>{const connection=await pool.getConnection();try{await connection.beginTransaction();const [reward]=await connection.query<any[]>('SELECT * FROM rewards WHERE id=? AND active=TRUE FOR UPDATE',[req.params.id]);const [points]=await connection.query<any[]>('SELECT * FROM reward_points WHERE user_id=? FOR UPDATE',[req.authUser!.id]);if(!reward[0]){await connection.rollback();return res.status(404).json({error:'Reward not found.'});}if(Number(points[0]?.balance||0)<Number(reward[0].points_cost)){await connection.rollback();return res.status(409).json({error:'Insufficient points.'});}await connection.query('UPDATE reward_points SET balance=balance-? WHERE user_id=?',[reward[0].points_cost,req.authUser!.id]);const [result]=await connection.query<any>('INSERT INTO reward_redemptions(user_id,reward_id,points_spent) VALUES(?,?,?)',[req.authUser!.id,reward[0].id,reward[0].points_cost]);await connection.query("INSERT INTO reward_transactions(user_id,points,transaction_type,reference_type,reference_id,description) VALUES(?,?,'redeemed','redemption',?,'Reward redemption')",[req.authUser!.id,-reward[0].points_cost,result.insertId]);await connection.commit();res.status(201).json({data:{id:result.insertId,status:'pending'}});}catch(error){await connection.rollback();throw error;}finally{connection.release();}});

enterpriseRoutes.get('/campaigns',async(_req,res)=>{const [rows]=await pool.query('SELECT c.*,u.full_name created_by_name,COUNT(cp.user_id) participants FROM campaigns c JOIN users u ON u.id=c.created_by LEFT JOIN campaign_participants cp ON cp.campaign_id=c.id GROUP BY c.id ORDER BY c.starts_at DESC,c.id DESC');res.json({data:rows});});
enterpriseRoutes.post('/campaigns',managers,async(req,res)=>{const parsed=z.object({title:z.string().min(3),description:z.string().min(10),campaignType:z.string().min(2),status:z.enum(['draft','published','active']).default('draft'),municipalityId:z.number().int().nullable().optional(),startsAt:z.string().datetime().nullable().optional(),endsAt:z.string().datetime().nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid campaign.',fields:parsed.error.flatten().fieldErrors});const [result]=await pool.query<any>('INSERT INTO campaigns(title,description,campaign_type,status,municipality_id,starts_at,ends_at,created_by) VALUES(?,?,?,?,?,?,?,?)',[parsed.data.title,parsed.data.description,parsed.data.campaignType,parsed.data.status,parsed.data.municipalityId||null,parsed.data.startsAt?new Date(parsed.data.startsAt):null,parsed.data.endsAt?new Date(parsed.data.endsAt):null,req.authUser!.id]);res.status(201).json({data:{id:result.insertId,...parsed.data}});});
enterpriseRoutes.post('/campaigns/:id/join',async(req,res)=>{await pool.query('INSERT INTO campaign_participants(campaign_id,user_id) VALUES(?,?) ON DUPLICATE KEY UPDATE status=\'registered\'',[req.params.id,req.authUser!.id]);res.status(204).end();});

enterpriseRoutes.get('/community/posts',async(_req,res)=>{const [rows]=await pool.query("SELECT p.*,u.full_name,COUNT(DISTINCT c.id) comments,COUNT(DISTINCT r.user_id) reactions FROM community_posts p JOIN users u ON u.id=p.user_id LEFT JOIN comments c ON c.post_id=p.id AND c.status='published' LEFT JOIN reactions r ON r.post_id=p.id WHERE p.status='published' GROUP BY p.id ORDER BY p.created_at DESC LIMIT 100");res.json({data:rows});});
enterpriseRoutes.post('/community/posts',async(req,res)=>{const parsed=z.object({title:z.string().min(3).max(190),body:z.string().min(3).max(10000)}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid community post.'});const [result]=await pool.query<any>('INSERT INTO community_posts(user_id,title,body) VALUES(?,?,?)',[req.authUser!.id,parsed.data.title,parsed.data.body]);res.status(201).json({data:{id:result.insertId,...parsed.data}});});
enterpriseRoutes.post('/community/posts/:id/comments',async(req,res)=>{const body=z.string().min(1).max(5000).safeParse(req.body?.body);if(!body.success)return res.status(422).json({error:'Comment is required.'});const [result]=await pool.query<any>('INSERT INTO comments(post_id,user_id,body) VALUES(?,?,?)',[req.params.id,req.authUser!.id,body.data]);res.status(201).json({data:{id:result.insertId,body:body.data}});});
enterpriseRoutes.put('/community/posts/:id/reaction',async(req,res)=>{const reaction=z.enum(['like','support','celebrate']).safeParse(req.body?.reaction);if(!reaction.success)return res.status(422).json({error:'Invalid reaction.'});await pool.query('INSERT INTO reactions(post_id,user_id,reaction_type) VALUES(?,?,?) ON DUPLICATE KEY UPDATE reaction_type=VALUES(reaction_type)',[req.params.id,req.authUser!.id,reaction.data]);res.status(204).end();});

for(const [pathName,table] of [['fleet/vehicles','vehicles'],['assets','assets'],['contractors','contractors'],['documents','document_library']] as const) enterpriseRoutes.get(`/${pathName}`,async(_req,res)=>{const [rows]=await pool.query(`SELECT * FROM ${table} ORDER BY id DESC LIMIT 200`);res.json({data:rows});});

enterpriseRoutes.get('/notifications/providers',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT id,channel,provider_code,enabled,priority,created_at FROM notification_providers ORDER BY channel,priority');res.json({data:rows});});
enterpriseRoutes.patch('/notifications/providers/:id',authorize('NATIONAL_ADMIN'),async(req,res)=>{const parsed=z.object({enabled:z.boolean().optional(),priority:z.number().int().min(1).max(1000).optional()}).safeParse(req.body);if(!parsed.success||!Object.keys(parsed.data).length)return res.status(422).json({error:'Invalid provider update.'});const fields=Object.keys(parsed.data);await pool.query(`UPDATE notification_providers SET ${fields.map(key=>`${key}=?`).join(',')} WHERE id=?`,[...Object.values(parsed.data),req.params.id]);res.status(204).end();});
enterpriseRoutes.get('/notifications/jobs',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT * FROM notification_jobs ORDER BY created_at DESC LIMIT 200');res.json({data:rows});});
enterpriseRoutes.post('/notifications/jobs',managers,async(req,res)=>{const parsed=z.object({channel:z.enum(['email','sms','push']),recipient:z.string().min(3).max(255),title:z.string().min(1),body:z.string().min(1),notificationId:z.number().int().nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid delivery job.'});const [result]=await pool.query<any>('INSERT INTO notification_jobs(notification_id,channel,recipient,payload_json) VALUES(?,?,?,?)',[parsed.data.notificationId||null,parsed.data.channel,parsed.data.recipient,JSON.stringify({title:parsed.data.title,body:parsed.data.body})]);res.status(201).json({data:{id:result.insertId,status:'queued'}});});
enterpriseRoutes.post('/notifications/process-queue',admins,async(_req,res)=>res.json({data:await processNotificationQueue()}));

enterpriseRoutes.get('/backups',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT * FROM backups ORDER BY started_at DESC LIMIT 100');res.json({data:rows});});
enterpriseRoutes.post('/backups',admins,async(req,res)=>{const type=z.enum(['database','uploads','configuration','full']).safeParse(req.body?.type);if(!type.success)return res.status(422).json({error:'Invalid backup type.'});try{res.status(201).json({data:await createBackup(type.data,req.authUser!.id)});}catch(error){res.status(500).json({error:'Backup failed.',detail:error instanceof Error?error.message:'Unknown backup error.'});}});
enterpriseRoutes.post('/backups/enforce-retention',authorize('NATIONAL_ADMIN'),async(_req,res)=>res.json({data:{expired:await enforceRetention()}}));
enterpriseRoutes.post('/backups/:id/restore-request',admins,async(req,res)=>{const reason=z.string().min(10).max(2000).safeParse(req.body?.reason);if(!reason.success)return res.status(422).json({error:'Restore reason is required.'});const [result]=await pool.query<any>('INSERT INTO restore_requests(backup_id,requested_by,reason) VALUES(?,?,?)',[req.params.id,req.authUser!.id,reason.data]);res.status(201).json({data:{id:result.insertId,status:'pending'}});});

enterpriseRoutes.get('/gis/layers',async(_req,res)=>{const [rows]=await pool.query('SELECT * FROM gis_layers WHERE active=TRUE ORDER BY name');res.json({data:rows});});
enterpriseRoutes.get('/gis/markers',async(req,res)=>{const [rows]=await pool.query('SELECT * FROM gis_markers WHERE status=\'active\''+(req.query.layerId?' AND layer_id=?':'')+' ORDER BY created_at DESC LIMIT 2000',req.query.layerId?[req.query.layerId]:[]);res.json({data:rows});});
enterpriseRoutes.get('/gis/boundaries',async(_req,res)=>{const [rows]=await pool.query('SELECT * FROM gis_boundaries ORDER BY entity_type,entity_id');res.json({data:rows});});
enterpriseRoutes.get('/gis/communities',async(_req,res)=>{const [rows]=await pool.query('SELECT c.*,w.name ward_name,d.name district_name FROM communities c JOIN wards w ON w.id=c.ward_id JOIN districts d ON d.id=w.district_id ORDER BY d.name,w.name,c.name');res.json({data:rows});});

enterpriseRoutes.get('/security/events',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT se.*,u.email FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.created_at DESC LIMIT 200');res.json({data:rows});});
enterpriseRoutes.get('/uploads/scans',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT s.*,u.original_name,u.mime_type,u.size_bytes FROM upload_scans s JOIN uploads u ON u.id=s.upload_id ORDER BY s.id DESC LIMIT 200');res.json({data:rows});});
enterpriseRoutes.post('/uploads/process-scans',admins,async(_req,res)=>res.json({data:await processUploadScans()}));
enterpriseRoutes.post('/operations/run-maintenance',authorize('NATIONAL_ADMIN'),async(_req,res)=>res.json({data:await runMaintenanceCycle()}));
enterpriseRoutes.get('/operations/metrics',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT metric_name,metric_value,unit,recorded_at FROM system_metrics ORDER BY recorded_at DESC LIMIT 500');res.json({data:rows});});
enterpriseRoutes.get('/operations/logs',admins,async(req,res)=>{const level=z.enum(['info','warn','error']).optional().safeParse(req.query.level);if(!level.success)return res.status(422).json({error:'Invalid log level.'});const [rows]=await pool.query(`SELECT id,log_level,log_type,message,context_json,request_id,created_at FROM structured_logs ${level.data?'WHERE log_level=?':''} ORDER BY created_at DESC LIMIT 300`,level.data?[level.data]:[]);res.json({data:rows});});
enterpriseRoutes.get('/uploads/quarantine',admins,async(_req,res)=>{const [rows]=await pool.query('SELECT q.*,u.original_name,u.mime_type,u.sha256 FROM quarantined_files q JOIN uploads u ON u.id=q.upload_id ORDER BY q.quarantined_at DESC');res.json({data:rows});});
enterpriseRoutes.get('/operations/health',admins,async(_req,res)=>{const started=Date.now();await pool.query('SELECT 1');const [[queue],[uploads],[sessions],[backups],[security]]=await Promise.all([pool.query<any[]>("SELECT SUM(status='queued') queued,SUM(status='processing') processing,SUM(status='dead') dead FROM notification_jobs"),pool.query<any[]>("SELECT COUNT(*) pending FROM upload_scans WHERE status IN ('queued','error','unavailable')"),pool.query<any[]>('SELECT COUNT(*) active FROM user_sessions WHERE revoked_at IS NULL AND expires_at>NOW()'),pool.query<any[]>("SELECT MAX(completed_at) latest,SUM(status='failed') failed FROM backups"),pool.query<any[]>("SELECT COUNT(*) unresolved FROM security_events WHERE resolved_at IS NULL AND severity IN ('high','critical')")]);const memory=process.memoryUsage();const data={status:'operational',api:{uptimeSeconds:Math.round(process.uptime()),memoryRssMb:Number((memory.rss/1048576).toFixed(2)),heapUsedMb:Number((memory.heapUsed/1048576).toFixed(2))},database:{status:'connected',latencyMs:Date.now()-started},queue:queue[0],uploads:uploads[0],sessions:sessions[0],backups:backups[0],security:security[0],checkedAt:new Date().toISOString()};await pool.query("INSERT INTO system_metrics(metric_name,metric_value,unit) VALUES('database.latency',?,'ms'),('api.memory.rss',?,'MB'),('api.memory.heap',?,'MB')",[data.database.latencyMs,data.api.memoryRssMb,data.api.heapUsedMb]);res.json({data});});
