import { pool } from './db.js';

const [done]=await pool.query<any[]>("SELECT id FROM normalization_runs WHERE migration_code='phase4_operational_state_v1'");
if(done[0]){console.log('Phase 4 operational-state normalization already completed.');await pool.end();process.exit(0);}
const [rows]=await pool.query<any[]>('SELECT state_key,value_json FROM operational_states');
const state=new Map<string,any>(rows.map(row=>{let value=row.value_json;for(let i=0;i<2&&typeof value==='string';i++){try{value=JSON.parse(value);}catch{break;}}return [row.state_key,value];}));
const [admins]=await pool.query<any[]>("SELECT id FROM users WHERE email='admin@ecoclean.sl' LIMIT 1");
const [citizens]=await pool.query<any[]>("SELECT id FROM users WHERE email='citizen@ecoclean.sl' LIMIT 1");
const adminId=admins[0].id,citizenId=citizens[0].id;let migrated=0;
for(const item of state.get('eco_fleet')||[]){await pool.query("INSERT INTO vehicles(registration_number,vehicle_type,status,metadata_json) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE vehicle_type=VALUES(vehicle_type),status=VALUES(status),metadata_json=VALUES(metadata_json)",[item.plate,item.type,String(item.status||'active').toLowerCase()==='offline'?'retired':String(item.status||'active').toLowerCase(),JSON.stringify(item)]);migrated++;}
for(const item of state.get('eco_assets')||[]){await pool.query("INSERT INTO assets(asset_code,name,asset_type,status,acquired_at,metadata_json) VALUES(?,?,?,'active',?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),metadata_json=VALUES(metadata_json)",[item.id,item.name,item.category,item.purchaseDate||null,JSON.stringify(item)]);migrated++;}
for(const item of state.get('eco_contractors')||[]){const status=String(item.status||'pending').toLowerCase()==='active'?'active':'pending';await pool.query('INSERT INTO contractors(name,registration_number,status,sla_json) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),status=VALUES(status),sla_json=VALUES(sla_json)',[item.name,item.id,status,JSON.stringify(item)]);migrated++;}
for(const item of state.get('eco_docs')||[]){const [categories]=await pool.query<any[]>('SELECT id FROM document_categories WHERE name=?',[item.category]);let categoryId=categories[0]?.id;if(!categoryId){const [result]=await pool.query<any>('INSERT INTO document_categories(name) VALUES(?)',[item.category]);categoryId=result.insertId;}await pool.query('INSERT INTO document_library(category_id,title,description,visibility,published_by,published_at) SELECT ?,?,?,\'authenticated\',?,? WHERE NOT EXISTS(SELECT 1 FROM document_library WHERE title=?)',[categoryId,item.title,`Published by ${item.author}`,adminId,item.publishedDate,item.title]);migrated++;}
for(const item of [...(state.get('eco_events')||[]),...(state.get('ecoclean_citizen_events')||[])]){const status=String(item.status||'published').toLowerCase();const normalized=['draft','published','active','completed','cancelled'].includes(status)?status:'published';await pool.query('INSERT INTO campaigns(title,description,campaign_type,status,starts_at,created_by) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM campaigns WHERE title=?)',[item.title,item.description||`Community activity at ${item.location||'an ECOCLEAN location'}`,item.category||'Community Cleanup',normalized,/^\d{4}-/.test(item.date||'')?item.date:null,adminId,item.title]);migrated++;}
for(const badge of state.get('ecoclean_citizen_badges')||[]){await pool.query('INSERT INTO rewards(code,name,description,points_cost,active) VALUES(?,?,?,?,TRUE) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description)',[badge.id,badge.name,badge.description,0]);migrated++;}
const points=Number(state.get('ecoclean_citizen_points')||0);await pool.query('INSERT INTO reward_points(user_id,balance,lifetime_earned) VALUES(?,?,?) ON DUPLICATE KEY UPDATE balance=VALUES(balance),lifetime_earned=GREATEST(lifetime_earned,VALUES(lifetime_earned))',[citizenId,points,points]);
await pool.query('INSERT INTO normalization_runs(migration_code,records_migrated,details_json) VALUES(?,?,?)',['phase4_operational_state_v1',migrated,JSON.stringify({sourceKeys:[...state.keys()]})]);
console.log(`Normalized ${migrated} legacy records into dedicated Phase 4 tables.`);await pool.end();
