import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { pool } from './db.js';
const run=promisify(execFile);
type Job={id:number;channel:'email'|'sms'|'push';recipient:string;payload_json:any;attempts:number;max_attempts:number};
type Result={reference:string};
const payload=(job:Job)=>typeof job.payload_json==='string'?JSON.parse(job.payload_json):job.payload_json;
async function send(job:Job,provider:string):Promise<Result>{const body=payload(job);if(provider==='smtp'){const message=`To: ${job.recipient}\nSubject: ${body.title||'ECOCLEAN SL'}\nContent-Type: text/plain; charset=utf-8\n\n${body.body||''}`;await run('/usr/sbin/sendmail',['-t'],{input:message} as any);return{reference:`smtp-${Date.now()}`};}
  const configs:any={sendgrid:{url:'https://api.sendgrid.com/v3/mail/send',token:process.env.SENDGRID_API_KEY},mailgun:{url:process.env.MAILGUN_API_URL,token:process.env.MAILGUN_API_KEY},twilio:{url:process.env.TWILIO_API_URL,token:process.env.TWILIO_AUTH_TOKEN},africas_talking:{url:process.env.AFRICAS_TALKING_API_URL,token:process.env.AFRICAS_TALKING_API_KEY},ecoclean_sms:{url:process.env.ECOCLEAN_SMS_URL,token:process.env.ECOCLEAN_SMS_TOKEN},fcm:{url:process.env.FCM_API_URL,token:process.env.FCM_SERVER_KEY},ecoclean_push:{url:process.env.ECOCLEAN_PUSH_URL,token:process.env.ECOCLEAN_PUSH_TOKEN}};const config=configs[provider];if(!config?.url||!config?.token)throw new Error(`${provider} is not configured.`);const response=await fetch(config.url,{method:'POST',headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json'},body:JSON.stringify({recipient:job.recipient,...body})});if(!response.ok)throw new Error(`${provider} returned HTTP ${response.status}`);return{reference:response.headers.get('x-message-id')||`${provider}-${Date.now()}`};}
export async function processNotificationQueue(limit=20){const [jobs]=await pool.query<any[]>("SELECT * FROM notification_jobs WHERE status='queued' AND available_at<=NOW() ORDER BY id LIMIT ?",[limit]);let delivered=0,failed=0;for(const job of jobs as Job[]){await pool.query("UPDATE notification_jobs SET status='processing',locked_at=NOW(),attempts=attempts+1 WHERE id=? AND status='queued'",[job.id]);const [providers]=await pool.query<any[]>("SELECT provider_code FROM notification_providers WHERE channel=? AND enabled=TRUE ORDER BY priority",[job.channel]);let result:Result|undefined,lastError='No enabled provider.';for(const candidate of providers){try{result=await send(job,candidate.provider_code);await pool.query("INSERT INTO notification_attempts(job_id,provider_code,status,response_reference) VALUES(?,?,'delivered',?)",[job.id,candidate.provider_code,result.reference]);break;}catch(error){lastError=error instanceof Error?error.message:'Provider failed';await pool.query("INSERT INTO notification_attempts(job_id,provider_code,status,error_message) VALUES(?,?,'failed',?)",[job.id,candidate.provider_code,lastError]);}}
    if(result){await pool.query("UPDATE notification_jobs SET status='delivered',last_error=NULL WHERE id=?",[job.id]);delivered++;}else{const next=job.attempts+1>=job.max_attempts?'dead':'queued';await pool.query("UPDATE notification_jobs SET status=?,last_error=?,available_at=DATE_ADD(NOW(),INTERVAL POW(2,attempts) MINUTE) WHERE id=?",[next,lastError,job.id]);failed++;}}
  return{processed:jobs.length,delivered,failed};}
