import fs from 'node:fs/promises';
import path from 'node:path';
import bcrypt from 'bcryptjs';
import { Router } from 'express';
import { z } from 'zod';
import { authenticate, authorize } from './auth.js';
import { pool } from './db.js';
import { accessibleUpload } from './mediaAccess.js';

export const userExperienceRoutes=Router();
userExperienceRoutes.use(authenticate);
const uploadRoot=path.resolve('storage/uploads');
const audit=async(userId:number,action:string,req:any,entityType?:string,entityId?:number,metadata?:unknown)=>pool.query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip_address,metadata_json) VALUES(?,?,?,?,?,?)',[userId,action,entityType||null,entityId||null,req.ip,metadata?JSON.stringify(metadata):null]);
const parseJson=(value:any,fallback:any)=>{if(value==null)return fallback;if(typeof value==='string'){try{return JSON.parse(value);}catch{return fallback;}}return value;};

userExperienceRoutes.get('/profile',async(req,res)=>{const [rows]=await pool.query<any[]>(`SELECT u.id,u.public_id,u.full_name fullName,u.email,u.phone,u.status,u.municipality_id municipalityId,u.district_id districtId,
  m.name municipality,d.name district,p.address,p.emergency_contact_name emergencyContactName,p.emergency_contact_phone emergencyContactPhone,p.biography,p.profile_upload_id profileUploadId,
  pref.theme,pref.language,pref.notification_preferences_json notificationPreferences,pref.gis_preferences_json gisPreferences,pref.dashboard_preferences_json dashboardPreferences
  FROM users u LEFT JOIN municipalities m ON m.id=u.municipality_id LEFT JOIN districts d ON d.id=u.district_id LEFT JOIN user_profiles p ON p.user_id=u.id LEFT JOIN user_preferences pref ON pref.user_id=u.id WHERE u.id=?`,[req.authUser!.id]);const data=rows[0];for(const key of ['notificationPreferences','gisPreferences','dashboardPreferences'])data[key]=parseJson(data[key],{});data.profileImageUrl=data.profileUploadId?`/api/uploads/${data.profileUploadId}`:null;res.json({data});});

userExperienceRoutes.patch('/profile',async(req,res)=>{if(req.authUser!.role==='STAFF')return res.status(403).json({error:'Staff identity details are managed by a Supervisor or Administrator.'});const parsed=z.object({fullName:z.string().min(3).max(160),email:z.string().email(),phone:z.string().min(7).max(40).nullable().optional(),address:z.string().max(255).nullable().optional(),municipalityId:z.number().int().nullable().optional(),districtId:z.number().int().nullable().optional(),emergencyContactName:z.string().max(160).nullable().optional(),emergencyContactPhone:z.string().max(40).nullable().optional(),biography:z.string().max(3000).nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid profile details.',fields:parsed.error.flatten().fieldErrors});const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.query('UPDATE users SET full_name=?,email=LOWER(?),phone=?,municipality_id=?,district_id=? WHERE id=?',[parsed.data.fullName,parsed.data.email,parsed.data.phone||null,parsed.data.municipalityId||null,parsed.data.districtId||null,req.authUser!.id]);await connection.query(`INSERT INTO user_profiles(user_id,address,emergency_contact_name,emergency_contact_phone,biography) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE address=VALUES(address),emergency_contact_name=VALUES(emergency_contact_name),emergency_contact_phone=VALUES(emergency_contact_phone),biography=VALUES(biography)`,[req.authUser!.id,parsed.data.address||null,parsed.data.emergencyContactName||null,parsed.data.emergencyContactPhone||null,parsed.data.biography||null]);await connection.commit();await audit(req.authUser!.id,'profile.updated',req,'user',req.authUser!.id);res.json({message:'Profile updated.'});}catch(error:any){await connection.rollback();res.status(error?.code==='ER_DUP_ENTRY'?409:500).json({error:error?.code==='ER_DUP_ENTRY'?'Email or phone is already registered.':'Profile update failed.'});}finally{connection.release();}});

userExperienceRoutes.put('/profile/preferences',async(req,res)=>{const parsed=z.object({theme:z.enum(['system','light','dark']).default('system'),language:z.string().min(2).max(20).default('en'),notificationPreferences:z.record(z.string(),z.boolean()).default({}),gisPreferences:z.record(z.string(),z.unknown()).default({}),dashboardPreferences:z.record(z.string(),z.unknown()).default({})}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid preferences.'});await pool.query(`INSERT INTO user_preferences(user_id,theme,language,notification_preferences_json,gis_preferences_json,dashboard_preferences_json) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE theme=VALUES(theme),language=VALUES(language),notification_preferences_json=VALUES(notification_preferences_json),gis_preferences_json=VALUES(gis_preferences_json),dashboard_preferences_json=VALUES(dashboard_preferences_json)`,[req.authUser!.id,parsed.data.theme,parsed.data.language,JSON.stringify(parsed.data.notificationPreferences),JSON.stringify(parsed.data.gisPreferences),JSON.stringify(parsed.data.dashboardPreferences)]);await audit(req.authUser!.id,'preferences.updated',req,'user',req.authUser!.id);res.status(204).end();});

userExperienceRoutes.post('/auth/change-password',async(req,res)=>{const parsed=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(10).max(128)}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Current password and a new password of at least 10 characters are required.'});const [rows]=await pool.query<any[]>('SELECT password_hash FROM users WHERE id=?',[req.authUser!.id]);if(!await bcrypt.compare(parsed.data.currentPassword,rows[0].password_hash))return res.status(401).json({error:'Current password is incorrect.'});if(await bcrypt.compare(parsed.data.newPassword,rows[0].password_hash))return res.status(422).json({error:'New password must be different.'});const hash=await bcrypt.hash(parsed.data.newPassword,12);await pool.query('UPDATE users SET password_hash=? WHERE id=?',[hash,req.authUser!.id]);await pool.query('UPDATE user_sessions SET revoked_at=NOW(),revoked_by=? WHERE user_id=?',[req.authUser!.id,req.authUser!.id]);await audit(req.authUser!.id,'password.changed',req,'user',req.authUser!.id);res.json({message:'Password changed. Sign in again with the new password.'});});

userExperienceRoutes.get('/uploads',async(req,res)=>{const reportId=req.query.reportId?Number(req.query.reportId):null;const [rows]=await pool.query<any[]>('SELECT id,public_id,report_id,task_id,ticket_id,purpose,original_name,mime_type,size_bytes,sha256,created_at FROM uploads WHERE owner_user_id=? AND deleted_at IS NULL'+(reportId?' AND report_id=?':'')+' ORDER BY created_at DESC',[req.authUser!.id,...(reportId?[reportId]:[])]);res.json({data:rows.map(row=>({...row,url:`/api/uploads/${row.id}`}))});});

userExperienceRoutes.delete('/uploads/:id',async(req,res)=>{const upload=await accessibleUpload(req.params.id,req.authUser!);if(!upload)return res.status(404).json({error:'Upload not found or access denied.'});const owner=upload.owner_user_id===req.authUser!.id;const admin=['ADMINISTRATOR','NATIONAL_ADMIN'].includes(req.authUser!.role);if(!owner&&!admin)return res.status(403).json({error:'Only the owner or an administrator can delete this upload.'});if(upload.report_id&&owner){const [report]=await pool.query<any[]>('SELECT status FROM reports WHERE id=? AND citizen_id=?',[upload.report_id,req.authUser!.id]);if(!report[0]||!['pending','under_review'].includes(report[0].status))return res.status(409).json({error:'Evidence cannot be deleted after assignment.'});}await pool.query('UPDATE user_profiles SET profile_upload_id=NULL WHERE profile_upload_id=?',[upload.id]);await pool.query('UPDATE uploads SET deleted_at=NOW() WHERE id=?',[upload.id]);await fs.rm(path.join(uploadRoot,path.basename(upload.stored_name)),{force:true});await audit(req.authUser!.id,'upload.deleted',req,'upload',upload.id);res.status(204).end();});

userExperienceRoutes.delete('/profile/photo',async(req,res)=>{const [rows]=await pool.query<any[]>('SELECT up.* FROM user_profiles p JOIN uploads up ON up.id=p.profile_upload_id WHERE p.user_id=?',[req.authUser!.id]);if(!rows[0])return res.status(204).end();await pool.query('UPDATE user_profiles SET profile_upload_id=NULL WHERE user_id=?',[req.authUser!.id]);await pool.query('UPDATE uploads SET deleted_at=NOW() WHERE id=?',[rows[0].id]);await fs.rm(path.join(uploadRoot,path.basename(rows[0].stored_name)),{force:true});await audit(req.authUser!.id,'profile.photo_deleted',req,'upload',rows[0].id);res.status(204).end();});

userExperienceRoutes.delete('/reports/:id',async(req,res)=>{const [rows]=await pool.query<any[]>('SELECT r.id,r.status,EXISTS(SELECT 1 FROM tasks t WHERE t.report_id=r.id) assigned FROM reports r WHERE r.id=? AND r.citizen_id=? AND r.deleted_at IS NULL',[req.params.id,req.authUser!.id]);if(!rows[0])return res.status(404).json({error:'Report not found.'});if(rows[0].assigned||!['pending','under_review'].includes(rows[0].status))return res.status(409).json({error:'Report cannot be deleted after assignment.'});await pool.query('UPDATE reports SET deleted_at=NOW() WHERE id=?',[req.params.id]);await pool.query('INSERT INTO report_history(report_id,actor_user_id,action,from_status,to_status) VALUES(?,?,\'deleted\',?,?)',[req.params.id,req.authUser!.id,rows[0].status,rows[0].status]);await audit(req.authUser!.id,'report.deleted',req,'report',Number(req.params.id));res.status(204).end();});

userExperienceRoutes.post('/support/tickets/:id/close',async(req,res)=>{const [rows]=await pool.query<any[]>('SELECT id,status FROM support_tickets WHERE id=? AND opened_by=?',[req.params.id,req.authUser!.id]);if(!rows[0])return res.status(404).json({error:'Ticket not found.'});if(!['resolved','open'].includes(rows[0].status))return res.status(409).json({error:'Ticket cannot be closed in its current state.'});await pool.query("UPDATE support_tickets SET status='closed',resolved_at=COALESCE(resolved_at,NOW()) WHERE id=?",[req.params.id]);await audit(req.authUser!.id,'ticket.closed',req,'support_ticket',Number(req.params.id));res.status(204).end();});

userExperienceRoutes.post('/admin/users',authorize('ADMINISTRATOR','NATIONAL_ADMIN'),async(req,res)=>{const parsed=z.object({fullName:z.string().min(3).max(160),email:z.string().email(),phone:z.string().min(7).max(40),password:z.string().min(10).max(128),role:z.enum(['CITIZEN','STAFF','SUPERVISOR','ADMINISTRATOR','NATIONAL_ADMIN']),municipalityId:z.number().int().nullable().optional(),districtId:z.number().int().nullable().optional()}).safeParse(req.body);if(!parsed.success)return res.status(422).json({error:'Invalid user registration.',fields:parsed.error.flatten().fieldErrors});if(parsed.data.role==='NATIONAL_ADMIN'&&req.authUser!.role!=='NATIONAL_ADMIN')return res.status(403).json({error:'Only a National Administrator can create this role.'});try{const hash=await bcrypt.hash(parsed.data.password,12);const [result]=await pool.query<any>(`INSERT INTO users(full_name,email,phone,password_hash,role_id,municipality_id,district_id,status) SELECT ?,LOWER(?),?,?,id,?,?,'active' FROM roles WHERE code=?`,[parsed.data.fullName,parsed.data.email,parsed.data.phone,hash,parsed.data.municipalityId||null,parsed.data.districtId||null,parsed.data.role]);await pool.query('INSERT IGNORE INTO user_profiles(user_id) VALUES(?)',[result.insertId]);await pool.query('INSERT IGNORE INTO user_preferences(user_id) VALUES(?)',[result.insertId]);await pool.query("INSERT INTO notifications(user_id,type,title,body) VALUES(?,'account_created','ECOCLEAN account created',?)",[result.insertId,`Your ${parsed.data.role} account is active.`]);await audit(req.authUser!.id,'user.created',req,'user',result.insertId,{role:parsed.data.role});res.status(201).json({data:{id:result.insertId,email:parsed.data.email,role:parsed.data.role}});}catch(error:any){res.status(error?.code==='ER_DUP_ENTRY'?409:500).json({error:error?.code==='ER_DUP_ENTRY'?'Email or phone is already registered.':'User creation failed.'});}});

userExperienceRoutes.patch('/admin/users/:id',authorize('ADMINISTRATOR','NATIONAL_ADMIN'),async(req,res)=>{const parsed=z.object({status:z.enum(['pending','active','suspended','disabled']).optional(),role:z.enum(['CITIZEN','STAFF','SUPERVISOR','ADMINISTRATOR','NATIONAL_ADMIN']).optional(),municipalityId:z.number().int().nullable().optional(),districtId:z.number().int().nullable().optional()}).safeParse(req.body);if(!parsed.success||!Object.keys(parsed.data).length)return res.status(422).json({error:'Invalid user update.'});if(parsed.data.role==='NATIONAL_ADMIN'&&req.authUser!.role!=='NATIONAL_ADMIN')return res.status(403).json({error:'Only a National Administrator can grant this role.'});if(String(req.authUser!.id)===req.params.id&&parsed.data.status&&parsed.data.status!=='active')return res.status(409).json({error:'You cannot disable your current account.'});if(parsed.data.role)await pool.query('UPDATE users SET role_id=(SELECT id FROM roles WHERE code=?) WHERE id=?',[parsed.data.role,req.params.id]);const updates:any={};if(parsed.data.status)updates.status=parsed.data.status;if('municipalityId'in parsed.data)updates.municipality_id=parsed.data.municipalityId;if('districtId'in parsed.data)updates.district_id=parsed.data.districtId;const fields=Object.keys(updates);if(fields.length)await pool.query(`UPDATE users SET ${fields.map(key=>`${key}=?`).join(',')} WHERE id=?`,[...Object.values(updates),req.params.id]);if(parsed.data.status&&parsed.data.status!=='active')await pool.query('UPDATE user_sessions SET revoked_at=NOW(),revoked_by=? WHERE user_id=? AND revoked_at IS NULL',[req.authUser!.id,req.params.id]);await audit(req.authUser!.id,'user.updated',req,'user',Number(req.params.id),parsed.data);res.status(204).end();});

userExperienceRoutes.get('/notification-deliveries',async(req,res)=>{const [rows]=await pool.query('SELECT d.* FROM notification_deliveries d JOIN notifications n ON n.id=d.notification_id WHERE n.user_id=? ORDER BY d.id DESC LIMIT 200',[req.authUser!.id]);res.json({data:rows});});
