CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id),
  FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS municipalities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE, status ENUM('active','inactive') DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS districts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, municipality_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE,
  FOREIGN KEY(municipality_id) REFERENCES municipalities(id) ON DELETE SET NULL, INDEX(municipality_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS wards (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, district_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE,
  FOREIGN KEY(district_id) REFERENCES districts(id) ON DELETE RESTRICT, INDEX(district_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS zones (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ward_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(40) NOT NULL UNIQUE,
  FOREIGN KEY(ward_id) REFERENCES wards(id) ON DELETE RESTRICT, INDEX(ward_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(36) NOT NULL DEFAULT (UUID()), role_id BIGINT UNSIGNED NOT NULL,
  municipality_id BIGINT UNSIGNED NULL, district_id BIGINT UNSIGNED NULL, full_name VARCHAR(160) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
  phone VARCHAR(40) NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, status ENUM('pending','active','suspended','disabled') DEFAULT 'active',
  email_verified_at TIMESTAMP NULL, last_login_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL,
  UNIQUE(public_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT,
  FOREIGN KEY(municipality_id) REFERENCES municipalities(id) ON DELETE SET NULL, FOREIGN KEY(district_id) REFERENCES districts(id) ON DELETE SET NULL,
  INDEX(role_id,status), INDEX(municipality_id,district_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(50) NOT NULL UNIQUE, citizen_id BIGINT UNSIGNED NOT NULL,
  municipality_id BIGINT UNSIGNED NULL, district_id BIGINT UNSIGNED NULL, ward_id BIGINT UNSIGNED NULL, zone_id BIGINT UNSIGNED NULL,
  title VARCHAR(190) NOT NULL, description TEXT NOT NULL, category VARCHAR(80) NOT NULL, priority ENUM('low','medium','high','critical') DEFAULT 'medium',
  status ENUM('pending','under_review','assigned','in_progress','completed','verified','closed','rejected') DEFAULT 'pending',
  latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, address TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL,
  FOREIGN KEY(citizen_id) REFERENCES users(id) ON DELETE RESTRICT, FOREIGN KEY(municipality_id) REFERENCES municipalities(id) ON DELETE SET NULL,
  FOREIGN KEY(district_id) REFERENCES districts(id) ON DELETE SET NULL, FOREIGN KEY(ward_id) REFERENCES wards(id) ON DELETE SET NULL,
  FOREIGN KEY(zone_id) REFERENCES zones(id) ON DELETE SET NULL, INDEX(citizen_id,status), INDEX(status,priority), INDEX(latitude,longitude)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(50) NOT NULL UNIQUE, report_id BIGINT UNSIGNED NULL,
  assigned_to BIGINT UNSIGNED NULL, assigned_by BIGINT UNSIGNED NULL, title VARCHAR(190) NOT NULL, description TEXT NULL,
  status ENUM('assigned','accepted','in_progress','completed','verified','cancelled') DEFAULT 'assigned', priority ENUM('low','medium','high','critical') DEFAULT 'medium',
  due_at TIMESTAMP NULL, completed_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE SET NULL, FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY(assigned_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(assigned_to,status), INDEX(report_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, type VARCHAR(80) NOT NULL, title VARCHAR(190) NOT NULL,
  body TEXT NOT NULL, data_json JSON NULL, read_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,read_at,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(80) NULL,
  entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(45) NULL, metadata_json JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(user_id,created_at), INDEX(action,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,expires_at)
) ENGINE=InnoDB;
