ALTER TABLE uploads ADD COLUMN content_blob LONGBLOB NULL AFTER sha256;

CREATE TABLE IF NOT EXISTS report_conversations (
  report_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  conversation_id BIGINT UNSIGNED NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE CASCADE,
  FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB;
