import React,{useEffect,useRef,useState} from 'react';
import {Check,Mic,Square,Volume2} from 'lucide-react';
import {speechService} from '../lib/services';

const languageOptions=[['en','English'],['kri','Krio'],['tem','Temne'],['men','Mende']] as const;

export function SpeakButton({text,language='en'}:{text:string;language?:string}){
  const [playing,setPlaying]=useState(false);
  const speak=async()=>{if(!text.trim()||playing)return;setPlaying(true);try{const capability=await speechService.capabilities();if(capability.data.enabled){const blob=await speechService.synthesize(text,language);const url=URL.createObjectURL(blob);const audio=new Audio(url);audio.onended=()=>{URL.revokeObjectURL(url);setPlaying(false);};audio.onerror=()=>{URL.revokeObjectURL(url);setPlaying(false);};await audio.play();return;}if('speechSynthesis'in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=language==='en'?'en-GB':'en-SL';utterance.rate=.92;utterance.onend=()=>setPlaying(false);utterance.onerror=()=>setPlaying(false);window.speechSynthesis.speak(utterance);return;}throw new Error('Audio playback is unavailable on this device.');}catch(error){setPlaying(false);alert(error instanceof Error?error.message:'Audio playback failed.');}};
  return <button type="button" onClick={speak} disabled={!text.trim()||playing} className="inline-flex items-center gap-1 text-[10px] font-bold text-brand-primary hover:text-brand-secondary disabled:opacity-40" aria-label="Listen to this text"><Volume2 className="w-3.5 h-3.5"/>{playing?'Playing…':'Listen'}</button>;
}

export function VoiceInput({onAccept,label='Speak instead of typing'}:{onAccept:(english:string,original:string,language:string)=>void;label?:string}){
  const [language,setLanguage]=useState('kri');const [consent,setConsent]=useState(false);const [recording,setRecording]=useState(false);const [processing,setProcessing]=useState(false);const [notice,setNotice]=useState('');const [result,setResult]=useState<any>(null);const recorder=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const timeout=useRef<number|undefined>(undefined);
  useEffect(()=>()=>{if(timeout.current)window.clearTimeout(timeout.current);recorder.current?.stream.getTracks().forEach(track=>track.stop());},[]);
  const finish=()=>{if(recorder.current?.state==='recording')recorder.current.stop();};
  const start=async()=>{setNotice('');setResult(null);if(!consent){setNotice('Confirm voice-processing consent before recording.');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setNotice('Microphone recording is not supported by this browser.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});chunks.current=[];const active=new MediaRecorder(stream);recorder.current=active;active.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data);};active.onstop=async()=>{stream.getTracks().forEach(track=>track.stop());setRecording(false);setProcessing(true);try{const mime=(active.mimeType||'audio/webm').split(';')[0];const extension=mime==='audio/mp4'?'m4a':mime==='audio/ogg'?'ogg':mime.includes('wav')?'wav':'webm';const blob=new Blob(chunks.current,{type:mime});const file=new File([blob],`voice-${Date.now()}.${extension}`,{type:mime});const response=await speechService.transcribe(file,language);setResult(response.data);}catch(error){setNotice(error instanceof Error?error.message:'Voice transcription failed.');}finally{setProcessing(false);}};active.start(250);setRecording(true);timeout.current=window.setTimeout(finish,60000);}catch{setNotice('Microphone permission was denied. You can continue typing normally.');}};
  const accept=async()=>{if(!result)return;await speechService.confirm(result.id);onAccept(result.englishTranslation,result.originalTranscript,result.language);setResult(null);setNotice('Voice text confirmed and added.');};
  return <div className="rounded-xl border border-emerald-100 bg-emerald-50/50 p-3 space-y-2">
    <div className="flex flex-wrap items-center gap-2"><select value={language} onChange={e=>setLanguage(e.target.value)} disabled={recording||processing} className="rounded-lg border border-emerald-200 bg-white px-2 py-1.5 text-[11px] font-bold text-gray-700">{languageOptions.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select><button type="button" onClick={recording?finish:start} disabled={processing} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-[11px] font-bold text-white ${recording?'bg-red-600':'bg-brand-primary'} disabled:opacity-50`}>{recording?<><Square className="w-3 h-3"/>Stop</>:<><Mic className="w-3.5 h-3.5"/>{processing?'Translating…':label}</>}</button><label className="flex items-center gap-1.5 text-[10px] text-gray-600"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={recording}/><span>I consent to secure voice processing. Audio is not retained.</span></label></div>
    {notice&&<p className="text-[10px] font-semibold text-amber-700" role="status">{notice}</p>}
    {result&&<div className="rounded-lg bg-white border border-emerald-100 p-3 space-y-2"><p className="text-[10px] font-bold uppercase text-gray-400">Original {result.languageName}</p><p className="text-xs text-gray-700">{result.originalTranscript}</p>{result.language!=='en'&&<><p className="text-[10px] font-bold uppercase text-gray-400">English translation</p><p className="text-xs text-gray-800 font-semibold">{result.englishTranslation}</p></>}<div className="flex gap-3"><SpeakButton text={result.englishTranslation}/><button type="button" onClick={accept} className="inline-flex items-center gap-1 text-[10px] font-bold text-brand-primary"><Check className="w-3.5 h-3.5"/>Confirm and use English</button></div></div>}
  </div>;
}
